### PR TITLE
PYTHON-SDK-V1-Updates-6.11.18

### PR DESCRIPTION
**Pull request by jpvajda**
Ran new code gen to update this SDK for v1.

### CODE REVIEW

**Comment by jpvajda** [comment]
@run-o  Are you ok If I merge this in now?

**Comment by ebodine-jump** [comment]
cool with me

**Comment by run-o** [comment]
@jpvajda Sure, let's merge it. We should also update the code for v2 and then we can do a release with both updates.

**Comment by jpvajda** [comment]
@run-o v2 didn't have updates, i ran the code gen but no files had changed since the last commit.

**Pull request merged**
